<?php

declare(strict_types=1);

namespace SimdJsonPolyfill\Strategy;

/**
 * Auto-prepend strategy - generates a PHP file for php.ini auto_prepend_file directive.
 *
 * Creates a file that can be auto-prepended to all PHP scripts via php.ini configuration.
 * Provides instructions for manual php.ini setup.
 */
final class AutoPrependStrategy implements StrategyInterface
{
    private bool $enabled = false;

    public function isAvailable(): bool
    {
        return extension_loaded('simdjson');
    }

    public function enable(array $config = []): void
    {
        if (!$this->isAvailable()) {
            throw new \RuntimeException(
                'AutoPrependStrategy requires ext-simdjson to be installed.'
            );
        }

        $outputFile = $config['output_file'] ?? sys_get_temp_dir() . '/simdjson-polyfill-prepend.php';

        $this->generatePrependFile($outputFile);
        $this->enabled = true;

        // Provide instructions
        $this->printInstructions($outputFile);
    }

    public function decode(
        string $json,
        ?bool $associative = null,
        int $depth = 512,
        int $flags = 0
    ): mixed {
        $polyfill = new PolyfillStrategy();
        return $polyfill->decode($json, $associative, $depth, $flags);
    }

    public function getName(): string
    {
        return 'auto-prepend';
    }

    public function getPriority(): int
    {
        return 30; // Low-medium priority
    }

    /**
     * Generate the auto-prepend file.
     *
     * @param string $outputFile
     */
    private function generatePrependFile(string $outputFile): void
    {
        $code = $this->generatePrependCode();

        $dir = dirname($outputFile);
        if (!is_dir($dir) && !mkdir($dir, 0755, true)) {
            throw new \RuntimeException("Failed to create directory: {$dir}");
        }

        if (file_put_contents($outputFile, $code) === false) {
            throw new \RuntimeException("Failed to write prepend file: {$outputFile}");
        }

        chmod($outputFile, 0644);
    }

    /**
     * Generate the prepend file code.
     *
     * @return string
     */
    private function generatePrependCode(): string
    {
        return <<<'PHP'
<?php

declare(strict_types=1);

/**
 * SimdJsonPolyfill auto-prepend file
 * This file is automatically included before every PHP script.
 *
 * Auto-generated by SimdJsonPolyfill\Strategy\AutoPrependStrategy
 */

// Only override if simdjson extension is loaded
if (extension_loaded('simdjson')) {
    /**
     * Backup original json_decode as __json_decode_native
     */
    if (!function_exists('__json_decode_native')) {
        function __json_decode_native(
            string $json,
            ?bool $associative = null,
            int $depth = 512,
            int $flags = 0
        ): mixed {
            return \json_decode($json, $associative, $depth, $flags);
        }
    }

    /**
     * Override json_decode with simdjson-powered version
     * Note: This only works if called before any other code uses json_decode
     */
    if (!function_exists('json_decode')) {
        function json_decode(
            string $json,
            ?bool $associative = null,
            int $depth = 512,
            int $flags = 0
        ): mixed {
            try {
                $assoc = $associative ?? false;
                $result = \simdjson_decode($json, $assoc, $depth);

                if ($result === null && $flags & JSON_THROW_ON_ERROR) {
                    $error = \json_last_error();
                    if ($error !== JSON_ERROR_NONE) {
                        throw new \JsonException(\json_last_error_msg(), $error);
                    }
                }

                return $result;
            } catch (\Exception $e) {
                if ($flags & JSON_THROW_ON_ERROR) {
                    throw new \JsonException($e->getMessage(), $e->getCode(), $e);
                }
                return null;
            }
        }
    }
}

PHP;
    }

    /**
     * Print setup instructions to the user.
     *
     * @param string $outputFile
     */
    private function printInstructions(string $outputFile): void
    {
        $instructions = <<<TEXT

========================================================================
AutoPrependStrategy Setup Instructions
========================================================================

The auto-prepend file has been generated at:
{$outputFile}

To enable it, add this line to your php.ini configuration:

auto_prepend_file = "{$outputFile}"

You can find your php.ini file location by running:
php --ini

After updating php.ini, restart your web server/PHP-FPM:
- Apache: sudo service apache2 restart
- Nginx: sudo service php-fpm restart
- PHP built-in server: restart the server

⚠️  WARNING: This will affect ALL PHP scripts on the system.
Only use this strategy if you understand the implications.

========================================================================

TEXT;

        // Log to stderr so it doesn't interfere with normal output
        fwrite(STDERR, $instructions);
    }
}
